### PR TITLE
Add PhD Alumni Section on Team Page

### PR DESCRIPTION
**Pull request by domoritz**
This pull request introduces a new section for PhD alumni on the `team.html` page of the cmudig.github.io repository.

- **Adds a "PhD Alumni" section**: A dedicated section titled "PhD Alumni" is added before the "Past Members" section to list alumni who were PhD students, sorted by their `alumni_since` year in descending order.
- **Filters PhD alumni**: Only alumni with the role of "PhD Student" and a specified `alumni_since` year are included in the new "PhD Alumni" section.
- **Updates the "Past Members" section**: The existing "Past Members" section is modified to exclude PhD alumni, ensuring they are only listed in the new "PhD Alumni" section.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/cmudig/cmudig.github.io?shareId=92832979-8efd-4994-a4ff-0cd0f0a8418e).

### CODE REVIEW

**Comment by domoritz** [comment]
This is the result of this pull request. Maybe we want to include something about graduation in the filter?

Screenshot 2024-06-06 at 11 17 21

**Comment by domoritz** [comment]
What do you think @adamperer @cabreraalex

**Comment by adamperer** [comment]
This is a good design, but I think it should only include Ph.D. students who finished their Ph.D.s in DIG (i.e. Alex would be alone).  The current design makes it seem like the others have their Ph.D.s, which is not the case.   What do you think @domoritz?

**Comment by domoritz** [comment]
Makes sense to me. I wonder how we can indicate that. Maybe we add a new flag phd_graduate.

**Pull request merged**
