### PR TITLE
Homepage heading animation

### PR DESCRIPTION
**Pull request by venkatesh-sivaraman**
Thoughts, feedback?

https://github.com/cmudig/cmudig.github.io/assets/13065028/331ab2d7-1f82-4b97-a489-cb64911b1b10

### CODE REVIEW

**Comment by adamperer** [comment]
I like it -- it's a great idea to use counterpoint for this!   Minor nit, but it feels a bit overwhelming with so many colors.  Perhaps the node colors could animate to match nicely with the animating background color of the header? 🤷

**Comment by domoritz** [comment]
I like the direction as well and agree that it's a bit overwhelming. I'd suggest trying to remove the animated background now that we have the graph. 

Another possible thing to animate would be a bunch of area charts similar to some of the animated keynote templates. I suggest that since we do more line charts than graphs in the group ;-)

**Comment by venkatesh-sivaraman** [comment]
A potential alternative (I kept the background animation since now the charts don't have color):

https://github.com/cmudig/cmudig.github.io/assets/13065028/6db2ac81-d3fb-4860-98df-9a425a503a7c

**Comment by domoritz** [comment]
I like the alternative!

**Comment by adamperer** [comment]
I like it too!  I'm going to merge.

**Pull request merged**
