### PR TITLE
add logo image set

### PR DESCRIPTION
**Pull request by C-Lion**
I looked at your website & made this logo that I think fits your organization. The sections of the cat are different data points that alone may not seem related, but as a whole make up the cat. I also tried to use CMU's colors.

### CODE REVIEW

**Comment by domoritz** [comment]
Thank you for the logo. I think I want to iterate a bit more on it but this is a nice start.

image

**Comment by C-Lion** [comment]
I assumed that would be the case. The colors are not exactly the CMU colors for starters & its a bit big. Based on the logo of your parent org I assume you wanted something a bit more modern/casual, but as with essays, its easier to edit something that exists than it is to start from scratch. All those files are created automatically by the tool, & are tiny, so I saw no reason not to share the whole folder so you can see what is produced. Assuming we stay with that tool, all those files can be regenerated with a click & downloaded.

**Comment by domoritz** [comment]
What tool did you use?

**Comment by domoritz** [comment]
We are drafting logos in #1. I’m going to close this pull request.

**Pull request closed without merging**
