### PR TITLE
fix header for different screen sizes

### PR DESCRIPTION
**Pull request by cabreraalex**
Tries to solve #63 by centering menu for medium screens.

### CODE REVIEW

**Comment by domoritz** [comment]
I don't think this works. The menu looks wrong on medium screens now. 

Screen Shot 2021-03-04 at 14 43 49

**Comment by cabreraalex** [comment]
"medium" is a big category so smaller mediums it only fits on different lines. let me see though

**Comment by cabreraalex** [comment]
Okay the other option is having the menus and social links stacked on the left - idk if that looks better

**Comment by domoritz** [comment]
How about https://github.com/cmudig/cmudig.github.io/pull/66?

**Pull request closed without merging**
