### PR TITLE
Add Yiwei Wu

### PR DESCRIPTION
**Pull request by yiwei-w**

### CODE REVIEW

**Comment by domoritz** [comment]
Thank you. The picture seems pretty large. Is it 400x400 as suggested in https://github.com/cmudig/cmudig.github.io/tree/master/_people#adding-a-person? (somehow the picture doesn't load in the GitHub preview right now).

**Comment by yiwei-w** [comment]
Sorry I forgot to check the image size. I have updated it to match the 400x400 requirement.

**Comment by domoritz** [comment]
Can you make sure the image is valid? I see this at https://github.com/yiwei-w/cmudig.github.io/blob/add-yiweiw/assets/people/yiwei.jpg
Screen Shot 2021-11-20 at 22 29 31

**Comment by yiwei-w** [comment]
Sorry for the confusion. Something weird happened when converting from `heic` to `jpg`. The image should be valid now.

**Pull request merged**
