### PR TITLE
fix #63

### LINKED ISSUE #63: News menu item breaks layout at 568 pixels width
Screen Shot 2021-03-04 at 13 09 42

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by cabreraalex** [comment]
Supposed to be like this? 
Screen Shot 2021-03-04 at 9 13 07 AM

**Comment by domoritz** [comment]
Which part? I think that's roughly what it looked like before we had news as well, no?

**Comment by cabreraalex** [comment]
The second line overlapping menu doesn't look great to me but it's not the worst. idk if centered is better.

**Comment by venkatesh-sivaraman** [comment]
Shouldn't we be using a collapsible navigation menu on mobile anyway...?

**Comment by domoritz** [comment]
> Shouldn't we be using a collapsible navigation menu on mobile anyway...?

Personally, I'm not a fan of collapsible menus. I would rather keep the menu small.

**Comment by domoritz** [comment]
> The second line overlapping menu doesn't look great to me but it's not the worst. idk if centered is better.

What do you mean?

**Comment by cabreraalex** [comment]
> > The second line overlapping menu doesn't look great to me but it's not the worst. idk if centered is better.
> 
> What do you mean?

the about and team tabs being right under the logo

**Comment by domoritz** [comment]
> > > The second line overlapping menu doesn't look great to me but it's not the worst. idk if centered is better.
> > 
> > What do you mean?

> the about and team tabs being right under the logo

I like it ;-) It looks like the dog is digging the letters.

**Review by venkatesh-sivaraman — COMMENTED** [review]
Suggested compromise:

1. Use `flex-wrap` instead of `flex-column` on the entire header bar so the nav only wraps to a new line when it needs to
2. Increase padding around the "CMU DIG" logo (`pb4-ns pb3 pr3`) so Scotty isn't quite so close to the navigation items

https://user-images.githubusercontent.com/13065028/110175306-89e32880-7dcf-11eb-999c-357580d7fb58.mov

**Comment by domoritz** [comment]
I like the flex wrap idea. Let's go with that. 

I liked that the dig was kind of digging the text but I think I have been overruled so let's add some more padding. Maybe not quite as much as in the video, though ;-)

**Comment by domoritz** [comment]
@venkatesh-sivaraman can you put together a pull request for your fix?

**Pull request closed without merging**
